apiVersion: v1
kind: Service
metadata:
  name: echo-ip-service-external
  namespace: testworkload
spec:
  externalIPs:
  - 10.20.20.1
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo-ip
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: echo-ip-service
    namespace: testworkload
  spec:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: echo-ip
    sessionAffinity: None
    type: ClusterIP
